id: P010471
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23782
  title: གསུང་འབུམ། ཡེ་ཤེས་རྡོ་རྗེ
  author: ''
  volumes:
    e9a0e31c445e4ecb8536e01dc9a945de:
      image_group_id: I2761
      title: ''
      volume_number: 1
      total_pages: 666
      base_file: v001.txt
