id: I70707FE2
legacy_id: P010471
ocr_import_info:
  bdrc_scan_id: W23782
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T02:48:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:45:03.650100+00:00'
last_modified: 2022-09-02 12:45:21.359270
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23782
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23782
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཡེ་ཤེས་རྡོ་རྗེ།
  author: འབྲུག་ཆེན ༠༡་གཙང་པ་རྒྱ་རས་ཡེ་ཤེས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7984547295675225
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I2761:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2761
      total_pages: 666
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2761.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7984547295675225
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
