id: I70707FE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:53:11+00:00'
last_modified: '2022-06-08T13:50:57.913450+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23782
  title: གསུང་འབུམ། ཡེ་ཤེས་རྡོ་རྗེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BB2D:
      image_group_id: I2761
      title: ''
      total_pages: 666
      order: 1
      base_file: BB2D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
